
language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - LIBCMAES=ON NLOPT=ON
    - LIBCMAES=ON NLOPT=OFF
    - LIBCMAES=OFF NLOPT=ON
    - LIBCMAES=OFF NLOPT=OFF

addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev
    - libtbb-dev
    - libgtest-dev
    - autoconf
    - automake
    - libtool
    - libgoogle-glog-dev
    - libgflags-dev

install:
  - if [ "$LIBCMAES" = "ON" ]; then 'ci/install_libcmaes.sh' ; fi
  - if [ "$NLOPT" = "ON"]; then 'ci/install_nlopt.sh' ; fi


# Change this to your needs
script:
  - ./waf configure
  - ./waf --tests --alltests -v
