
language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - LIBCMAES=ON NLOPT=ON TBB=ON EXPERIMENTAL=OFF SFERES=OFF PYTHON=python3
    - LIBCMAES=ON NLOPT=ON TBB=ON EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=ON TBB=OFF EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=ON TBB=ON EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=ON TBB=OFF EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=OFF SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=OFF PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=OFF PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=ON PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=ON PYTHON=python2
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=ON PYTHON=python2
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=ON PYTHON=python2

addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev
    - python
    - python3

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

install:
  - if [ "$LIBCMAES" = "ON" ]; then 'ci/install_libcmaes.sh' ; fi
  - if [ "$NLOPT" = "ON" ]; then 'ci/install_nlopt.sh' ; fi
  - if [ "$TBB" = "ON" ]; then 'ci/install_tbb.sh' ; fi
  - if [ "$SFERES" = "ON" ]; then 'ci/install_sferes.sh' ; fi


# Change this to your needs
script:
  - if [ "$SFERES" = "OFF" ]; then $PYTHON ./waf configure ; else $PYTHON ./waf configure --sferes=$CI_HOME/sferes2 ; fi
  - if [ "$EXPERIMENTAL" = "OFF" ]; then $PYTHON ./waf --tests --alltests -v ; else $PYTHON ./waf --experimental ; fi
