
language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`

addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev
    - libtbb-dev
    - libgtest-dev
    - autoconf
    - automake
    - libtool
    - libgoogle-glog-dev
    - libgflags-dev

install:
  - cd /usr/src/gtest
  - sudo mkdir build && cd build
  - sudo cmake ..
  - sudo make
  - sudo cp *.a /usr/lib
  - cd
  - git clone https://github.com/beniz/libcmaes.git
  - cd libcmaes
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd
  - cd $CI_HOME
  - sudo ldconfig


# Change this to your needs
script:
  - ./waf configure
  - ./waf --tests --alltests -v
  - ./build/src/tests/test_optimizers
  - ./build/src/tests/test_init_functions
  - ./build/src/tests/test_cmaes
