
language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - LIBCMAES=ON NLOPT=ON TBB=ON
    - LIBCMAES=ON NLOPT=ON TBB=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=ON
    - LIBCMAES=ON NLOPT=OFF TBB=OFF
    - LIBCMAES=OFF NLOPT=ON TBB=ON
    - LIBCMAES=OFF NLOPT=ON TBB=OFF
    - LIBCMAES=OFF NLOPT=OFF TBB=ON
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF
    - LIBCMAES=ON NLOPT=ON TBB=ON EXTENSIVE=ON

addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev

install:
  - if [ "$LIBCMAES" = "ON" ]; then 'ci/install_libcmaes.sh' ; fi
  - if [ "$NLOPT" = "ON" ]; then 'ci/install_nlopt.sh' ; fi
  - if [ "$TBB" = "ON" ]; then 'ci/install_tbb.sh' ; fi


# Change this to your needs
script:
  - ./waf configure
  - ./waf --tests --alltests -v
  - if [ "$EXTENSIVE" = "ON" ]; then 'ci/run_extensive.sh' ; fi
